name: release-please

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: release-please-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-please:
    uses: spark-match/spark-match-01-devops/.github/workflows/reusable-release-please.yml@v0.1.18
    secrets:
      release-please-app-id: ${{ secrets.RELEASE_PLEASE_APP_ID }}
      release-please-app-private-key: ${{ secrets.RELEASE_PLEASE_APP_PRIVATE_KEY }}
